# Nightly test of scipy, against the nightly build of Python
name: Nightly build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_nightly:

#    if: "github.repository == 'scipy/scipy' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

#    - name: Install Python 3.9
#      if: matrix.python-version == '3.9'
#      run: |
#        sudo add-apt-repository ppa:deadsnakes/ppa
#        sudo apt-get update
#        sudo apt-get install -y --no-install-recommends python3.9-dev python3.9-distutils python3.9-venv
#        python3.9 -m pip install --upgrade pip setuptools

    - name: Install other build dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        sudo apt-get install -y --no-install-recommends libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache libmpc-dev

    - name: ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")

    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
        path: $GITHUB_WORKSPACE/.ccache
        key: ${{ matrix.config.name }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ matrix.config.name }}-ccache-

    - name: ccache setup
      run: |
        # Update symlinks
        sudo /usr/sbin/update-ccache-symlinks
        # Prepend ccache into the PATH
        echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
        # Source bashrc to test the new PATH
        source ~/.bashrc && echo $PATH

    - name: Install packages
      run: |
        python -m pip install --user numpy setuptools wheel cython pytest pytest-xdist pybind11 pytest-xdist

    - name: Test SciPy
      env:
        CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
        CCACHE_COMPRESS: "true"
        CCACHE_COMPRESSLEVEL: "6"
        CCACHE_MAXSIZE: "400M"
      run: |
        python tools/suppress_output.py python setup.py build
        python tools/suppress_output.py pip wheel --no-build-isolation .
#        pip install --no-cache-dir scipy*.whl
#        python -u runtests.py -g -j2 -m fast --no-build -- -rfEX --durations=10
#        print statistics for ccache
        ccache -s
